const trailData = {
  TX: [
  {
    "projectName": "DENISON DAM - LAKE TEXOMA, TX AND OK",
    "areaName": "JUNIPER POINT",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "Yes",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 33.85933,
    "long": -96.83813,
    "tap": 1,
    "length": 15.0,
    "eGain": 1286,
    "intensity": "moderate",
    "infoLink": "https://www.alltrails.com/trail/us/texas/cross-timbers-hiking-trail",
    "comments": ""
  },
  {
    "projectName": "DENISON DAM - LAKE TEXOMA, TX AND OK",
    "areaName": "PAW PAW CREEK ACCESS POINT",
    "isWalking": "Yes",
    "isEquestrian": "",
    "isBiking": "",
    "isWheelchair": "",
    "isPet": "",
    "lat": 33.855417,
    "long": -96.897918,
    "tap": 1,
    "length": -1,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "DENISON DAM - LAKE TEXOMA, TX AND OK",
    "areaName": "PLATTER FLATS",
    "isWalking": "Yes",
    "isEquestrian": "Yes",
    "isBiking": "No",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 33.92242,
    "long": -96.54249,
    "tap": 1,
    "length": 6.3,
    "eGain": 229,
    "intensity": "moderate",
    "infoLink": "https://www.alltrails.com/parks/us/oklahoma/platter-flats-equestrian-park",
    "comments": ""
  },
  {
    "projectName": "DENISON DAM - LAKE TEXOMA, TX AND OK",
    "areaName": "BUNCOMBE CREEK",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "No",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 33.5335,
    "long": -96.4821,
    "tap": 2,
    "length": 1.5,
    "eGain": -1,
    "intensity": "easy",
    "infoLink": "",
    "comments": "No link yet. Will be soon!"
  }
],

  OK: [
  {
    "projectName": "ARCADIA LAKE",
    "areaName": "DAMSITE",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "Yes",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 35.65234,
    "long": -97.36566,
    "tap": 2,
    "length": 1.3,
    "eGain": 68,
    "intensity": "Easy",
    "infoLink": "https://www.alltrails.com/trail/us/oklahoma/arcadia-lake-east-loop",
    "comments": ""
  },
  {
    "projectName": "CANTON LAKE",
    "areaName": "Frank Raab Nature Trail",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "Yes",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": -100,
    "long": -200,
    "tap": 1,
    "length": 1.8,
    "eGain": -1,
    "intensity": "Easy",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "COPAN LAKE",
    "areaName": "COPAN POINT",
    "isWalking": "Yes",
    "isEquestrian": "Yes",
    "isBiking": "No",
    "isWheelchair": "No",
    "isPet": "No",
    "lat": 36.88764,
    "long": -95.94549,
    "tap": 1,
    "length": 8.2,
    "eGain": 442,
    "intensity": "Easy",
    "infoLink": "https://www.alltrails.com/explore/trail/us/oklahoma/copan-lake-trail",
    "comments": ""
  },
  {
    "projectName": "COPAN LAKE",
    "areaName": "WASHINGTON COVE",
    "isWalking": "Yes",
    "isEquestrian": "Yes",
    "isBiking": "Yes",
    "isWheelchair": "No",
    "isPet": "Yes on a leash",
    "lat": 36.5438,
    "long": -95.5608,
    "tap": 2,
    "length": 4.0,
    "eGain": -1,
    "intensity": "Easy",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "EUFAULA LAKE",
    "areaName": "LADYBIRD LANDING",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "No",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 35.29416,
    "long": -95.3675,
    "tap": 2,
    "length": 0.75,
    "eGain": -1,
    "intensity": "Easy",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "EUFAULA LAKE",
    "areaName": "BEN O CARROLL OVERLOOK",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "No",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 35.300764,
    "long": -95.363853,
    "tap": 1,
    "length": 2.3,
    "eGain": 272,
    "intensity": "Moderate",
    "infoLink": "https://www.alltrails.com/trail/us/oklahoma/younger-bend-trail",
    "comments": "Loop"
  },
  {
    "projectName": "EUFAULA LAKE",
    "areaName": "EUFAULA COVE NORTH",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "Yes",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 35.2858,
    "long": -95.57117,
    "tap": 1,
    "length": 0.7,
    "eGain": -1,
    "intensity": "Easy",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "FORT SUPPLY LAKE",
    "areaName": "SUPPLY PARK",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "Yea",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 36.549327,
    "long": -99.575865,
    "tap": 1,
    "length": 0.3,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "HEYBURN LAKE",
    "areaName": "SHEPPARD POINT",
    "isWalking": "Yes",
    "isEquestrian": "",
    "isBiking": "",
    "isWheelchair": "",
    "isPet": "",
    "lat": 35.959079,
    "long": -96.317901,
    "tap": 1,
    "length": 9.0,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "KAW LAKE",
    "areaName": "OSAGE COVE",
    "isWalking": "Yes",
    "isEquestrian": "Yes",
    "isBiking": "Yes",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 36.713114,
    "long": -96.89818,
    "tap": 1,
    "length": 2.5,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "KAW LAKE",
    "areaName": "SARGE CREEK",
    "isWalking": "Yes",
    "isEquestrian": "Yes",
    "isBiking": "Yes",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 36.767256,
    "long": -96.808034,
    "tap": 1,
    "length": 13.0,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "KAW LAKE",
    "areaName": "BURBANK LANDING",
    "isWalking": "Yes",
    "isEquestrian": "",
    "isBiking": "",
    "isWheelchair": "",
    "isPet": "",
    "lat": 36.740438,
    "long": -96.850749,
    "tap": 1,
    "length": -1,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "KEYSTONE LAKE",
    "areaName": "WALNUT CREEK PARK",
    "isWalking": "Yes",
    "isEquestrian": "Yes",
    "isBiking": "Yes",
    "isWheelchair": "No",
    "isPet": "Yes if on a leash.",
    "lat": 36.252825,
    "long": -96.27994,
    "tap": 3,
    "length": 7.0,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "KEYSTONE LAKE",
    "areaName": "WASHINGTON IRVING SOUTH",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "No",
    "isWheelchair": "No",
    "isPet": "Yes if on a leash.",
    "lat": 36.199663,
    "long": -96.258522,
    "tap": 1,
    "length": 1.0,
    "eGain": 72,
    "intensity": "Easy",
    "infoLink": "https://www.alltrails.com/trail/us/oklahoma/washington-irving-scenic-trail--2",
    "comments": ""
  },
  {
    "projectName": "KEYSTONE LAKE",
    "areaName": "BRUSH CREEK",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "Yes",
    "isWheelchair": "No",
    "isPet": "Yes if on a leash.",
    "lat": -100,
    "long": -200,
    "tap": 2,
    "length": 1.0,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "KEYSTONE LAKE",
    "areaName": "WHITEWATER",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "Yes",
    "isWheelchair": "No",
    "isPet": "Yes if on a leash.",
    "lat": 36.139114,
    "long": -96.259793,
    "tap": 2,
    "length": 5.0,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "KEYSTONE LAKE",
    "areaName": "DAM SITE",
    "isWalking": "Yes",
    "isEquestrian": "",
    "isBiking": "",
    "isWheelchair": "",
    "isPet": "",
    "lat": 36.150521,
    "long": -96.248198,
    "tap": 1,
    "length": 3.0,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "KEYSTONE LAKE",
    "areaName": "APPALACHIA BAY",
    "isWalking": "No ORV and ATV only",
    "isEquestrian": "No",
    "isBiking": "No",
    "isWheelchair": "No",
    "isPet": "No",
    "lat": 36.182388,
    "long": -96.292367,
    "tap": 1,
    "length": 10.0,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": "ORV"
  },
  {
    "projectName": "OOLOGAH LAKE",
    "areaName": "SPENCER CREEK",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "No",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 36.510976,
    "long": -95.56105,
    "tap": 1,
    "length": 1.5,
    "eGain": 108,
    "intensity": "Easy",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "OOLOGAH LAKE",
    "areaName": "BLUE CREEK",
    "isWalking": "Yes",
    "isEquestrian": "Yes",
    "isBiking": "No",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 36.452291,
    "long": -95.588571,
    "tap": 6,
    "length": 18.0,
    "eGain": 232,
    "intensity": "Easy",
    "infoLink": "https://www.alltrails.com/trail/us/oklahoma/will-rogers-centennial-trail",
    "comments": ""
  },
  {
    "projectName": "OOLOGAH LAKE",
    "areaName": "HAWTHORN BLUFF",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "Yes",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 36.434145,
    "long": -95.676203,
    "tap": 1,
    "length": 2.0,
    "eGain": 265,
    "intensity": "Easy",
    "infoLink": "https://www.alltrails.com/trail/us/oklahoma/skull-hollow-nature-trail",
    "comments": ""
  },
  {
    "projectName": "PINE CREEK LAKE",
    "areaName": "OFFICE COMPOUND",
    "isWalking": "Yes",
    "isEquestrian": "",
    "isBiking": "",
    "isWheelchair": "",
    "isPet": "",
    "lat": 34.10517,
    "long": -95.087992,
    "tap": 1,
    "length": 1.2,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "PINE CREEK LAKE",
    "areaName": "LITTLE RIVER PARK",
    "isWalking": "Yes",
    "isEquestrian": "",
    "isBiking": "",
    "isWheelchair": "",
    "isPet": "",
    "lat": 34.170293,
    "long": -95.124734,
    "tap": 2,
    "length": -1,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "ROBERT S KERR L&D, RES & PWRHSE-MCCLELLAN-KERR ARK R NAV SYS",
    "areaName": "SHORT MOUNTAIN COVE",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "No",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 35.322231,
    "long": -94.780944,
    "tap": 1,
    "length": 2.2,
    "eGain": 416,
    "intensity": "moderate",
    "infoLink": "https://www.alltrails.com/trail/us/oklahoma/arkansas-river-short-mountain-trail",
    "comments": ""
  },
  {
    "projectName": "SARDIS LAKE",
    "areaName": "POTATO HILLS CENTRAL",
    "isWalking": "Yes",
    "isEquestrian": "Yes",
    "isBiking": "Yes",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 34.401398,
    "long": -200,
    "tap": 2,
    "length": 21.0,
    "eGain": 141,
    "intensity": "Moderate",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "SARDIS LAKE",
    "areaName": "POTATO HILLS SOUTH",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "No",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 34.393347,
    "long": -200,
    "tap": 1,
    "length": 0.75,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "SKIATOOK LAKE OK",
    "areaName": "OSAGE PARK",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "Yes",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 36.378824,
    "long": -96.156882,
    "tap": 1,
    "length": 1.8,
    "eGain": 82,
    "intensity": "Moderate",
    "infoLink": "https://www.alltrails.com/trail/us/oklahoma/stay-gold-sunset-trail",
    "comments": ""
  },
  {
    "projectName": "TENKILLER FERRY LAKE",
    "areaName": "OVERLOOK",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "Yes",
    "isWheelchair": "No",
    "isPet": "Yes if on a leash.",
    "lat": 35.596929,
    "long": -95.052155,
    "tap": 2,
    "length": 2.2,
    "eGain": 187,
    "intensity": "Easy",
    "infoLink": "https://www.alltrails.com/trail/us/oklahoma/overlook-trail-at-tenkiller-ferry-lake",
    "comments": ""
  },
  {
    "projectName": "TENKILLER FERRY LAKE",
    "areaName": "CATO CREEK LANDING",
    "isWalking": "Yes",
    "isEquestrian": "",
    "isBiking": "",
    "isWheelchair": "",
    "isPet": "",
    "lat": 35.637754,
    "long": -94.978023,
    "tap": 1,
    "length": 2.5,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  }
],

  KS: [
  {
    "projectName": "COUNCIL GROVE LAKE",
    "areaName": "PIONEER NATURE TRAIL",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "yes",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 38.67611,
    "long": -96.51016,
    "tap": 1,
    "length": 1.25,
    "eGain": -1,
    "intensity": "Easy",
    "infoLink": "https://www.americantrails.org/resources/pioneer-nature-trail-kansas",
    "comments": "2 Loops"
  },
  {
    "projectName": "COUNCIL GROVE LAKE",
    "areaName": "OUTLET CHANNEL EAST",
    "isWalking": "Yes",
    "isEquestrian": "",
    "isBiking": "",
    "isWheelchair": "",
    "isPet": "",
    "lat": 38.68113,
    "long": -96.49657,
    "tap": 1,
    "length": -1,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "ELK CITY LAKE",
    "areaName": "CARD CREEK",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "Yes",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 37.25465,
    "long": -95.85007,
    "tap": 1,
    "length": 2.4,
    "eGain": 236,
    "intensity": "Easy",
    "infoLink": "https://www.alltrails.com/explore/trail/us/kansas/timber-ridge-trail",
    "comments": "Loop"
  },
  {
    "projectName": "JOHN REDMOND DAM AND RESERVOIR",
    "areaName": "RIVERSIDE WEST",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "Yes",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 38.238177,
    "long": -95.761129,
    "tap": 2,
    "length": 0.25,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "JOHN REDMOND DAM AND RESERVOIR",
    "areaName": "RIVERSIDE EAST",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "Yes",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 38.24283,
    "long": -95.751247,
    "tap": 3,
    "length": 1.5,
    "eGain": -1,
    "intensity": "easy",
    "infoLink": "https://www.swt.usace.army.mil/Locations/Tulsa-District-Lakes/Kansas/John-Redmond-Reservoir/John-Redmond-Reservoir-Recreation/",
    "comments": ""
  },
  {
    "projectName": "JOHN REDMOND DAM AND RESERVOIR",
    "areaName": "OVERLOOK",
    "isWalking": "Yes",
    "isEquestrian": "",
    "isBiking": "",
    "isWheelchair": "",
    "isPet": "",
    "lat": 38.250739,
    "long": -95.802661,
    "tap": 2,
    "length": -1,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "JOHN REDMOND DAM AND RESERVOIR",
    "areaName": "OTTER CREEK",
    "isWalking": "Yes",
    "isEquestrian": "",
    "isBiking": "",
    "isWheelchair": "",
    "isPet": "",
    "lat": 38.209362,
    "long": -95.802661,
    "tap": 2,
    "length": 9.5,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": "140 acers of trails for ORV."
  },
  {
    "projectName": "JOHN REDMOND DAM AND RESERVOIR",
    "areaName": "HICKORY CREEK EAST",
    "isWalking": "Yes",
    "isEquestrian": "",
    "isBiking": "",
    "isWheelchair": "",
    "isPet": "",
    "lat": 38.242821,
    "long": -95.7513,
    "tap": 1,
    "length": 12.0,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "JOHN REDMOND DAM AND RESERVOIR",
    "areaName": "DAM SITE",
    "isWalking": "Yes",
    "isEquestrian": "",
    "isBiking": "",
    "isWheelchair": "",
    "isPet": "",
    "lat": 38.249505,
    "long": -95.753914,
    "tap": 1,
    "length": -1,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "MARION RESERVOIR",
    "areaName": "COTTONWOOD POINT",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "Yes",
    "isWheelchair": "Yes",
    "isPet": "Yes",
    "lat": 38.393755,
    "long": -97.092196,
    "tap": 1,
    "length": 1.3,
    "eGain": 19,
    "intensity": "Easy",
    "infoLink": "https://www.alltrails.com/trail/us/kansas/willow-walk-trail--2",
    "comments": ""
  },
  {
    "projectName": "PEARSON-SKUBITZ BIG HILL LAKE",
    "areaName": "OVERLOOK",
    "isWalking": "Yes",
    "isEquestrian": "No",
    "isBiking": "Yes",
    "isWheelchair": "Yes",
    "isPet": "Yes",
    "lat": 37.27262,
    "long": -95.47047,
    "tap": 2,
    "length": 1.9,
    "eGain": 82,
    "intensity": "Easy",
    "infoLink": "https://www.alltrails.com/explore/trail/us/kansas/ruth-nixon-memorial-trail--2",
    "comments": "Out and Back"
  },
  {
    "projectName": "PEARSON-SKUBITZ BIG HILL LAKE",
    "areaName": "CHERRYVALE PARK",
    "isWalking": "Yes",
    "isEquestrian": "Yes",
    "isBiking": "Yes",
    "isWheelchair": "Yes",
    "isPet": "Yes",
    "lat": 37.277763,
    "long": -95.473254,
    "tap": 1,
    "length": 17.0,
    "eGain": 82,
    "intensity": "Easy",
    "infoLink": "https://www.alltrails.com/trail/us/kansas/ruth-nixon-memorial-trail--2",
    "comments": ""
  },
  {
    "projectName": "PEARSON-SKUBITZ BIG HILL LAKE",
    "areaName": "HWY 160 HORSE TRAIL",
    "isWalking": "Limited",
    "isEquestrian": "Yes",
    "isBiking": "Yes",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 37.336556,
    "long": -95.43825,
    "tap": 3,
    "length": 17.0,
    "eGain": -1,
    "intensity": "",
    "infoLink": "http://www.bchkansas.com/big-hill-chapter.html",
    "comments": "One Way"
  },
  {
    "projectName": "PEARSON-SKUBITZ BIG HILL LAKE",
    "areaName": "MOUND VALLEY",
    "isWalking": "Yes",
    "isEquestrian": "Yes",
    "isBiking": "Yes",
    "isWheelchair": "Yes",
    "isPet": "Yes",
    "lat": 37.266411,
    "long": -95.452727,
    "tap": 2,
    "length": 2.0,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  },
  {
    "projectName": "PEARSON-SKUBITZ BIG HILL LAKE",
    "areaName": "TIMBER HILL PARK",
    "isWalking": "Yes",
    "isEquestrian": "Yes",
    "isBiking": "Yes",
    "isWheelchair": "No",
    "isPet": "Yes",
    "lat": 37.295504,
    "long": -95.44782,
    "tap": 2,
    "length": 17.0,
    "eGain": -1,
    "intensity": "",
    "infoLink": "",
    "comments": ""
  }
]
};